"use strict";
var _a;
let d = "hassan";
let o = new String("hassan");
console.log(d === o);
let str = "5" + 2;
console.log(str);
let stra = "Hello";
console.log(stra);
let stre = "hello,World!";
console.log(stre.slice(0, 5));
let stry = "Hello,World!";
console.log(stry.substr(-3));
let num = 8;
let multiplier = 2;
num *= multiplier += 3;
console.log(num);
let r = "Hello";
let p = "hello";
let result = r < p;
console.log(result);
let u = true;
let l = 5;
let results = u && (l > 10);
console.log(results);
let names = "sheikh";
let fallbackNames = "Anonymous";
let resulta = (_a = names !== null && names !== void 0 ? names : fallbackNames) !== null && _a !== void 0 ? _a : "Guest";
console.log(resulta);
let t = undefined;
let m;
let resulto = t === m;
console.log(result);
let price = 10;
let discount = null;
let finalPrice = price - (discount !== null && discount !== void 0 ? discount : 0);
console.log(finalPrice);
let w = "hangi";
let resultu = w && "World";
console.log(resultu);
let e;
let resultr = e !== null ? w : "default";
console.log(resultr);
console.log(!!"0");
var x = " ";
console.log(Boolean(x));
