let myname;
myname = 90;
myname = null;
console.log(myname);
let myAge;
myAge = 18;
console.log(myAge);
// myAge="Dont know";
// console.log(myAge.toLocaleLowerCase());
let newAge = Math.random() > 0.6 ? "khan" : 60;
console.log(newAge);
export {};
